/**
 * Shared protocol/types for Web Worker communication.
 *
 * All messages between the main thread and workers use these types.
 * Workers are self-contained and cannot import from the main bundle,
 * so they re-declare the message types they need inline. This file
 * exists for the main thread to have a single source of truth.
 */

// ─── Pathfinding Worker ────────────────────────────────────────────────────

export interface PathfindingRequest {
  type: 'findPath';
  /** Map tiles indexed by "q,r" key with terrain info. */
  tiles: Record<string, { terrain: string }>;
  /** Starting hex. */
  from: { q: number; r: number };
  /** Destination hex. */
  to: { q: number; r: number };
  /** Available movement points. */
  movementPoints: number;
}

export interface PathfindingResponse {
  type: 'findPathResult';
  /** Shortest path from `from` to `to` (null if unreachable). */
  path: Array<{ q: number; r: number }> | null;
  /** All hexes reachable within `movementPoints`. */
  reachable: Array<{ q: number; r: number }>;
}

// ─── AI Worker ────────────────────────────────────────────────────────────

export interface AiRequest {
  type: 'generateTurn';
  /** Serialized GameState (plain object). */
  state: unknown;
  /** AI player generating commands. */
  playerId: string;
  /** Difficulty level affecting decision quality. */
  difficulty: string;
}

export interface AiResponse {
  type: 'generateTurnResult';
  /** Serialized GameCommand[] generated by the AI. */
  commands: unknown[];
}

// ─── MapGen Worker ────────────────────────────────────────────────────────

export interface MapGenRequest {
  type: 'generateMap';
  /** Map width in hexes. */
  width: number;
  /** Map height in hexes. */
  height: number;
  /** Random seed for deterministic generation. */
  seed: number;
  /** Number of players to place. */
  playerCount: number;
}

export interface MapGenResponse {
  type: 'generateMapResult';
  /** Serialized MapData (plain object). */
  mapData: unknown;
  /** Starting hex positions for each player. */
  startingPositions: Array<{ q: number; r: number }>;
}

// ─── Simulation Worker ───────────────────────────────────────────────────

export interface SimulationRequest {
  type: 'simulate';
  /** Serialized GameState. */
  state: unknown;
  /** Serialized GameCommand[] to apply. */
  commands: unknown[];
}

export interface SimulationResponse {
  type: 'simulateResult';
  /** Final state after applying all commands. */
  finalState: unknown;
  /** Events generated during simulation. */
  events: unknown[];
}

// ─── Error Response ──────────────────────────────────────────────────────

export interface WorkerErrorResponse {
  type: 'error';
  /** Original request type that caused the error. */
  requestType: string;
  /** Error message. */
  message: string;
}

// ─── Union types ──────────────────────────────────────────────────────────

export type WorkerRequest =
  | PathfindingRequest
  | AiRequest
  | MapGenRequest
  | SimulationRequest;

export type WorkerResponse =
  | PathfindingResponse
  | AiResponse
  | MapGenResponse
  | SimulationResponse
  | WorkerErrorResponse;
